name: namida
description: A Beautiful and Feature-rich Music Player, With YouTube & Video Support Built in Flutter
publish_to: "none"
version: 2.5.3-beta+240520195

environment:
  sdk: ">=3.1.4 <4.0.0"
  flutter: ^3.13.8

dependency_overrides:
  win32: ^3.0.0
  just_audio_platform_interface:
    git:
      url: https://github.com/MSOB7YY/just_audio
      path: just_audio_platform_interface/
      ref: video
  archive: ^3.3.8
  intl: ^0.18.0

dependencies:
  flutter:
    sdk: flutter

  # ---- Core ----
  get:
    git:
      url: https://github.com/MSOB7YY/getx
  permission_handler: ^11.0.1
  logger: ^2.2.0
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.2
  intl: ^0.18.0
  flutter_archive: ^5.0.0
  url_launcher: ^6.1.10
  connectivity_plus: ^4.0.2
  selectable_autolink_text: ^2.6.0
  share_plus: ^7.1.0
  calendar_date_picker2: ^0.5.2
  wakelock_plus: ^1.1.1
  flutter_local_notifications: ^15.1.0
  flutter_sharing_intent:
    git:
      url: https://github.com/MSOB7YY/flutter_sharing_intent
  queue: ^3.1.0+2
  jiffy: ^6.2.1
  playlist_manager:
    git:
      url: https://github.com/namidaco/playlist_manager
  history_manager:
    git:
      url: https://github.com/namidaco/history_manager
  flutter_html:
    git:
      url: https://github.com/zhourengui/flutter_html
  flutter_volume_controller: ^1.3.0
  flutter_markdown: ^0.6.17+3
  flutter_mailer: ^2.1.1
  lrc: ^1.0.2
  vibration: ^1.8.4
  flutter_displaymode: ^0.6.0

  # ---- Audio Indexing & Playback ----
  just_audio:
    git:
      url: https://github.com/MSOB7YY/just_audio
      path: just_audio/
      ref: video
  audio_service:
    git:
      url: https://github.com/MSOB7YY/audio_service
      path: audio_service/
  waveform_extractor: ^1.0.3
  basic_audio_handler:
    git:
      url: https://github.com/namidaco/basic_audio_handler
  on_audio_query:
    git:
      url: https://github.com/MSOB7YY/on_audio_query
      path: packages/on_audio_query

  # ---- Video Indexing & Playback ----
  ffmpeg_kit_flutter_min: "5.1.0-LTS"
  newpipeextractor_dart:
    git:
      url: https://github.com/MSOB7YY/NewPipeExtractor_Dart

  # ---- Image Utilities ----
  palette_generator: ^0.3.3+2
  photo_view: ^0.14.0

  # ---- UI Rendering ----
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_colorpicker: ^1.0.3
  animated_background: ^2.0.0
  known_extents_list_view_builder:
    git:
      url: https://github.com/MSOB7YY/known_extents_listview_fancy
  flutter_animate: ^4.2.0+1
  dynamic_color: ^1.6.7
  scrollable_positioned_list: ^0.3.8

  # ---- UI Widgets ----
  wheel_slider: "1.1.1"
  sleek_circular_slider: ^2.0.1
  checkmark: ^0.0.2+1
  like_button: ^2.0.5
  flutter_scrollbar_modified:
    git:
      url: https://github.com/MSOB7YY/flutter_scrollbar_modified
  sticky_headers: ^0.3.0+2
  flutter_sticky_header: ^0.6.5
  focused_menu: ^1.0.5
  paged_vertical_calendar: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  flutter_native_splash:

flutter_native_splash:
  image: assets/namida_icon.png
  image_dark: assets/namida_icon.png
  color: "#dfc6a7"
  color_dark: "#dfc6a7"
  android: true
  ios: false
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/language/langs.json
    - assets/language/translations/
    - assets/fonts/
    - assets/icons/
    - assets/logos/
    - assets/namida_icon.png
  fonts:
    - family: broken
      fonts:
        - asset: assets/fonts/broken.ttf
    - family: broken_filled
      fonts:
        - asset: assets/fonts/broken_filled.ttf
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca/LexendDeca-Black.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Bold.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-ExtraBold.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-ExtraLight.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Light.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Medium.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Regular.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-SemiBold.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Thin.ttf
