name: namida
description: A Beautiful and Feature-rich Music Player, With YouTube & Video Support Built in Flutter
publish_to: "none"
version: 5.0.17-beta+250224350

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ^3.29.0

dependency_overrides:
  intl: ^0.20.1

  flutter_js:
    git:
      url: https://github.com/MSOB7YY/flutter_js

  on_audio_query_platform_interface:
    git:
      url: https://github.com/MSOB7YY/on_audio_query
      path: packages/on_audio_query_platform_interface

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ---- Core ----
  nampack:
    git:
      url: https://github.com/MSOB7YY/nampack
  dart_extensions:
    git:
      url: https://github.com/MSOB7YY/dart_extensions
  path: ^1.9.0
  http: ^1.2.1
  path_provider: ^2.1.3
  permission_handler: ^11.0.1
  logger: ^2.2.0
  package_info_plus: ^8.0.0
  device_info_plus: ^11.1.0
  intl: ^0.20.1
  flutter_archive: ^6.0.3
  archive: ^4.0.3
  url_launcher: ^6.3.0
  connectivity_plus: ^6.0.3
  selectable_autolink_text: ^2.6.0
  share_plus: ^10.0.2
  calendar_date_picker2: ^1.0.2
  wakelock_plus: ^1.1.1
  screen_brightness: ^2.1.1
  home_widget: ^0.7.0
  flutter_local_notifications: ^19.0.0-dev.6
  flutter_sharing_intent:
    git:
      url: https://github.com/MSOB7YY/flutter_sharing_intent
  queue: ^3.1.0+2
  jiffy: ^6.2.1
  playlist_manager:
    git:
      url: https://github.com/namidaco/playlist_manager
  history_manager:
    git:
      url: https://github.com/namidaco/history_manager
  flutter_volume_controller: ^1.3.0
  flutter_markdown: ^0.7.1
  flutter_mailer: ^3.0.0
  lrc:
    git:
      url: https://github.com/MSOB7YY/dart_lrc
  vibration: ^3.1.3
  flutter_displaymode: ^0.6.0
  flutter_udid: ^4.0.0
  namico_db_wrapper:
    git:
      url: https://github.com/namidaco/namico_db_wrapper

  # ---- Audio Indexing & Playback ----
  just_audio:
    git:
      url: https://github.com/MSOB7YY/just_audio
      path: just_audio/
      ref: video
  audio_service:
    git:
      url: https://github.com/MSOB7YY/audio_service
      path: audio_service/
  waveform_extractor: ^1.1.3
  basic_audio_handler:
    git:
      url: https://github.com/namidaco/basic_audio_handler
  on_audio_query:
    git:
      url: https://github.com/MSOB7YY/on_audio_query
      path: packages/on_audio_query

  # ---- Video Indexing & Playback ----
  ffmpeg_kit_flutter:
    git:
      url: https://github.com/MSOB7YY/ffmpeg-kit
      path: flutter/flutter
  youtipie:
    git:
      url: https://github.com/namidaco/youtipie
  namico_login_manager:
    git:
      url: https://github.com/namidaco/namico_login_manager
  namico_subscription_manager:
    git:
      url: https://github.com/namidaco/namico_subscription_manager

  # ---- Image Utilities ----
  palette_generator: ^0.3.3+2
  photo_view: ^0.15.0

  # ---- UI Rendering ----
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_colorpicker: ^1.0.3
  animated_background: ^2.0.0
  flutter_animate: ^4.2.0+1
  dynamic_color: ^1.6.7
  scrollable_positioned_list: ^0.3.8

  # ---- UI Widgets ----
  wheel_slider: "1.1.1"
  sleek_circular_slider: ^2.0.1
  checkmark: ^0.0.2+1
  like_button: ^2.0.5
  flutter_scrollbar_modified:
    git:
      url: https://github.com/MSOB7YY/flutter_scrollbar_modified
  sticky_headers: ^0.3.0+2
  flutter_sticky_header:
    git:
      url: https://github.com/giangphan11/flutter_sticky_header
  focused_menu: ^1.0.5
  paged_vertical_calendar: ^1.1.6

  # ---- Windows Packages ----
  filepicker_windows: ^2.1.4
  just_audio_windows: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1

  custom_lint:
  obx_lints:
    git:
      url: https://github.com/MSOB7YY/nampack
      path: packages/obx_lints
  msix: ^3.16.8

flutter_native_splash:
  image: assets/namida_icon.png
  image_dark: assets/namida_icon.png
  color: "#dfc6a7"
  color_dark: "#121212"
  android: true
  ios: false
  web: false
  android_12:
    color: "#dfc6a7"
    color_dark: "#121212"

flutter:
  uses-material-design: true

  assets:
    - assets/language/langs.json
    - assets/language/translations/
    - assets/fonts/
    - assets/icons/
    - assets/logos/
    - assets/namida_icon.png
    - assets/namida_icon_monet.png
  fonts:
    - family: broken
      fonts:
        - asset: assets/fonts/broken.ttf
    - family: broken_filled
      fonts:
        - asset: assets/fonts/broken_filled.ttf
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca/LexendDeca-Black.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Bold.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-ExtraBold.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-ExtraLight.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Light.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Medium.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Regular.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-SemiBold.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Thin.ttf

msix_config:
  display_name: Namida
  publisher_display_name: namidaco
  identity_name: com.msob7y.namida
  logo_path: assets\namida_icon_monet.png
  capabilities: musicLibrary, videosLibrary, internetClient
  # certificate_path: .certificates\CERTIFICATE.pfx
  install_certificate: true
  file_extension: .audio, .music, .video
