name: namida
description: A Beautiful and Feature-rich Music Player, With YouTube & Video Support Built in Flutter
publish_to: "none"
version: 1.8.5+231203

environment:
  sdk: ">=3.1.4 <4.0.0"
  flutter: ^3.13.8

dependency_overrides:
  win32: ^3.0.0
  dart_extensions:
    git:
      url: https://github.com/MSOB7YY/dart_extensions
      ref: 1de0a3d597a20f9464fa36740a76e8c534d2200f
  archive: ^3.3.8
  intl: ^0.18.0

dependencies:
  flutter:
    sdk: flutter

  # ---- Core ----
  get:
    git:
      url: https://github.com/MSOB7YY/getx
  permission_handler: ^11.0.1
  device_info_plus: ^8.1.0
  intl: ^0.18.0
  flutter_archive: ^5.0.0
  url_launcher: ^6.1.10
  connectivity_plus: ^4.0.2
  selectable_autolink_text: ^2.6.0
  share_plus: ^7.1.0
  read_more_text: ^0.0.5
  calendar_date_picker2: ^0.5.2
  wakelock_plus: ^1.1.1
  flutter_local_notifications: ^15.1.0
  flutter_sharing_intent:
    git:
      url: https://github.com/MSOB7YY/flutter_sharing_intent
      ref: a6a9f135a64cbf3599e1333fd37e6b7eb249bbb9
  catcher:
    git:
      url: https://github.com/MSOB7YY/catcher
  queue: ^3.1.0+2
  jiffy: ^6.2.1
  playlist_manager:
    git:
      url: https://github.com/namidaco/playlist_manager
      ref: 35f89cbf7048bac92f0594a9ed2fc27696a81a89
  history_manager:
    git:
      url: https://github.com/namidaco/history_manager
      ref: dc5e7d51ce34e49bb7dfd9b45f13dff4418243f6
  flutter_html:
    git:
      url: https://github.com/zhourengui/flutter_html
  picture_in_picture:
    git:
      url: https://github.com/MSOB7YY/picture_in_picture
      ref: 8b1927af4781cb4a3b5e828053d42f404c79b947
  flutter_volume_controller: ^1.3.0
  flutter_markdown: ^0.6.17+3
  flutter_mailer: ^2.1.1
  lrc: ^1.0.2
  system_info2: ^4.0.0

  # ---- Path/File Providers ----
  path_provider: ^2.0.14
  external_path: ^1.0.3
  file_picker: "6.1.1"

  # ---- Audio Indexing & Playback ----
  just_audio:
    git:
      url: https://github.com/MSOB7YY/just_audio
      path: just_audio/
      ref: d507797ff4ebd37b05784cb962842b0e86f9170c
  audio_service:
    git:
      url: https://github.com/MSOB7YY/audio_service
      path: audio_service/
      ref: 5915657acb366aa2195b57bf9f10d35fda20c604
  faudiotagger:
    git:
      url: https://github.com/MSOB7YY/faudiotagger
      ref: cb8399eec6bc9d238e53125d294c9a3cb5b91434
  waveform_extractor: ^1.0.1
  basic_audio_handler:
    git:
      url: https://github.com/namidaco/basic_audio_handler
      ref: 167aa4c082958f93e45c55a01b521aef1455c68c
  on_audio_query:
    git:
      url: https://github.com/MSOB7YY/on_audio_query
      path: packages/on_audio_query
      ref: 69c7653e4b04ff24e657bee7b8706838e93303d7

  # ---- Video Indexing & Playback ----
  video_player:
    git:
      url: https://github.com/MSOB7YY/video_player_cache
      path: video_player/
      ref: ebd92a98f08f92ffa9daa080dcd6796785e12ad7
  ffmpeg_kit_flutter_min: "5.1.0-LTS"
  newpipeextractor_dart:
    git:
      url: https://github.com/MSOB7YY/NewPipeExtractor_Dart
      ref: 183f75193c02555971713557e956e453c4b6be4f

  # ---- Image Utilities ----
  extended_image: ^8.0.2
  palette_generator: ^0.3.3+2
  photo_view: ^0.14.0

  # ---- UI Rendering ----
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_colorpicker: ^1.0.3
  animated_background: ^2.0.0
  known_extents_list_view_builder:
    git:
      url: https://github.com/MSOB7YY/known_extents_listview_fancy
      ref: 95d9e56403b03f2f176bdceb269119d11cf7a4ef
  flutter_animate: ^4.2.0+1
  dynamic_color: ^1.6.7
  scrollable_positioned_list: ^0.3.8

  # ---- UI Widgets ----
  wheel_slider: "1.1.1"
  sleek_circular_slider: ^2.0.1
  checkmark: ^0.0.2+1
  like_button: ^2.0.5
  flutter_scrollbar_modified:
    git:
      url: https://github.com/MSOB7YY/flutter_scrollbar_modified
      ref: 3877cc37f184ba7f5caeeb64227e344925756791
  sticky_headers: ^0.3.0+2
  focused_menu: ^1.0.5
  paged_vertical_calendar: ^1.1.6

  # ---- Under Test ----
  # google_sign_in: ^6.0.2
  dio: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  flutter_native_splash:

flutter_native_splash:
  image: assets/namida_icon.png
  image_dark: assets/namida_icon.png
  color: "#dfc6a7"
  color_dark: "#dfc6a7"
  android: true
  ios: false
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/language/langs.json
    - assets/language/translations/
    - assets/fonts/
    - assets/icons/
    - assets/logos/
    - assets/namida_icon.png
  fonts:
    - family: broken
      fonts:
        - asset: assets/fonts/broken.ttf
    - family: broken_filled
      fonts:
        - asset: assets/fonts/broken_filled.ttf
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca/LexendDeca-Black.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Bold.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-ExtraBold.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-ExtraLight.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Light.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Medium.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Regular.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-SemiBold.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Thin.ttf
