display_name: Namida
generic_name: Media Player
icon: linux/icons/namida.png
metainfo: linux/packaging/com.msob7y.namida.metainfo.xml
startup_notify: true

categories:
  - AudioVideo
  - Audio
  - Video
  - Player
keywords:
  - Music
  - Video
  - Youtube
  - Media
  - Player
include:
  - libgtk-3.so.0
  - libgdk-3.so.0
  - libz.so.1
  - libpangocairo-1.0.so.0
  - libcairo-gobject.so.2
  - libgdk_pixbuf-2.0.so.0
  - libatk-1.0.so.0
  - libpango-1.0.so.0
  - libcairo.so.2
  - libharfbuzz.so.0
  - libgio-2.0.so.0
  - libgobject-2.0.so.0
  - libglib-2.0.so.0
  - libstdc++.so.6
  - libm.so.6
  - libgcc_s.so.1
  - libc.so.6
  - libasound.so.2
  - libepoxy.so.0
  - libcrypto.so.3
  - libdl.so.2
  - libfontconfig.so.1
  - libpthread.so.0
  - libgmodule-2.0.so.0
  - libpangoft2-1.0.so.0
  - libfribidi.so.0
  - libXi.so.6
  - libX11.so.6
  - libatk-bridge-2.0.so.0
  - libcloudproviders.so.0
  - libtinysparql-3.0.so.0
  - libXfixes.so.3
  - libxkbcommon.so.0
  - libwayland-client.so.0
  - libwayland-cursor.so.0
  - libwayland-egl.so.1
  - libXext.so.6
  - libXcursor.so.1
  - libXdamage.so.1
  - libXcomposite.so.1
  - libXrandr.so.2
  - libXinerama.so.1
  - libglycin-2.so.0
  - libthai.so.0
  - libpng16.so.16
  - libfreetype.so.6
  - libXrender.so.1
  - libxcb.so.1
  - libxcb-render.so.0
  - libxcb-shm.so.0
  - libpixman-1.so.0
  - libgraphite2.so.3
  - libmount.so.1
  - libffi.so.8
  - libpcre2-8.so.0
  - libass.so.9
  - libavcodec.so.62
  - libavfilter.so.11
  - libavformat.so.62
  - libavutil.so.60
  - libplacebo.so.351
  - libswresample.so.6
  - libswscale.so.9
  - libcdio_paranoia.so.2
  - libcdio_cdda.so.2
  - libcdio.so.19
  - libdvdnav.so.4
  - liblcms2.so.2
  - libarchive.so.13
  - libavdevice.so.62
  - libbluray.so.3
  - libluajit-5.1.so.2
  - librubberband.so.3
  - libSDL2-2.0.so.0
  - libuchardet.so.0
  - libvapoursynth-script.so.0
  - libzimg.so.2
  - libjack.so.0
  - libopenal.so.1
  - libpipewire-0.3.so.0
  - libpulse.so.0
  - libdrm.so.2
  - libdisplay-info.so.3
  - libgbm.so.1
  - libjpeg.so.8
  - libsixel.so.1
  - libXss.so.1
  - libXpresent.so.1
  - libXv.so.1
  - libGL.so.1
  - libEGL.so.1
  - libvulkan.so.1
  - libva-drm.so.2
  - libva.so.2
  - libva-wayland.so.2
  - libva-x11.so.2
  - libvdpau.so.1
  - libexpat.so.1
  - libatspi.so.0
  - libdbus-1.so.3
  - libjson-glib-1.0.so.0
  - libxml2.so.16
  - libsqlite3.so.0
  - libseccomp.so.2
  - libdatrie.so.1
  - libbz2.so.1.0
  - libbrotlidec.so.1
  - libXau.so.6
  - libXdmcp.so.6
  - libblkid.so.1
  - libunibreak.so.6
  - libvpx.so.11
  - libwebpmux.so.3
  - liblzma.so.5
  - libdav1d.so.7
  - libopencore-amrwb.so.0
  - librsvg-2.so.2
  - libsnappy.so.1
  - libaom.so.3
  - libgsm.so.1
  - libjxl.so.0.11
  - libjxl_threads.so.0.11
  - libmp3lame.so.0
  - libopencore-amrnb.so.0
  - libopenjp2.so.7
  - libopus.so.0
  - librav1e.so.0.8
  - libspeex.so.1
  - libSvtAv1Enc.so.3
  - libtheoraenc.so.2
  - libtheoradec.so.2
  - libvorbis.so.0
  - libvorbisenc.so.2
  - libwebp.so.7
  - libx264.so.165
  - libx265.so.215
  - libxvidcore.so.4
  - libglslang.so.16
  - libvpl.so.2
  - libbs2b.so.0
  - libvmaf.so.3
  - libvidstab.so.1.2
  - libzmq.so.5
  - libOpenCL.so.1
  - libdvdread.so.8
  - libmodplug.so.1
  - libopenmpt.so.0
  - libgmp.so.10
  - libgnutls.so.30
  - libsrt.so.1.5
  - libssh.so.4
  - libunwind.so.8
  - libshaderc_shared.so.1
  - libglslang-default-resource-limits.so.16
  - libdovi.so.3
  - libsoxr.so.0
  - libacl.so.1
  - libzstd.so.1
  - liblz4.so.1
  - libraw1394.so.11
  - libavc1394.so.0
  - librom1394.so.0
  - libiec61883.so.0
  - libxcb-shape.so.0
  - libxcb-xfixes.so.0
  - libv4l2.so.0
  - libfftw3.so.3
  - libsamplerate.so.0
  - libpython3.13.so.1.0
  - libpulsecommon-17.0.so
  - libcurl.so.4
  - libGLdispatch.so.0
  - libGLX.so.0
  - libX11-xcb.so.1
  - libxcb-dri3.so.0
  - libsystemd.so.0
  - libicuuc.so.78
  - libbrotlicommon.so.1
  - libjxl_cms.so.0.11
  - libhwy.so.1
  - libbrotlienc.so.1
  - libogg.so.0
  - libsharpyuv.so.0
  - libmvec.so.1
  - libSPIRV-Tools-opt.so
  - libSPIRV-Tools.so
  - libgomp.so.1
  - libsodium.so.26
  - libpgm-5.3.so.0
  - libmpg123.so.0
  - libvorbisfile.so.3
  - libleancrypto.so.1
  - libp11-kit.so.0
  - libidn2.so.0
  - libunistring.so.5
  - libtasn1.so.6
  - libhogweed.so.6
  - libnettle.so.8
  - libv4lconvert.so.0
  - libsndfile.so.1
  - libasyncns.so.0
  - libnghttp3.so.9
  - libnghttp2.so.14
  - libssh2.so.1
  - libpsl.so.5
  - libssl.so.3
  - libgssapi_krb5.so.2
  - libicudata.so.78
  - libFLAC.so.14
  - libkrb5.so.3
  - libk5crypto.so.3
  - libcom_err.so.2
  - libkrb5support.so.0
  - libkeyutils.so.1
  - libresolv.so.2
  - libfuse.so.2
  - libasound.so
  - libasound.so.2.0.0